#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_RauCu.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNongSan_CN")]
	public partial class dbQLNongsanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_DonDatHang(CT_DonDatHang instance);
    partial void UpdateCT_DonDatHang(CT_DonDatHang instance);
    partial void DeleteCT_DonDatHang(CT_DonDatHang instance);
    partial void InsertDonDatHang(DonDatHang instance);
    partial void UpdateDonDatHang(DonDatHang instance);
    partial void DeleteDonDatHang(DonDatHang instance);
    partial void InsertLoaiSanPham(LoaiSanPham instance);
    partial void UpdateLoaiSanPham(LoaiSanPham instance);
    partial void DeleteLoaiSanPham(LoaiSanPham instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertQuanTri(QuanTri instance);
    partial void UpdateQuanTri(QuanTri instance);
    partial void DeleteQuanTri(QuanTri instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    #endregion
		
		public dbQLNongsanDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLNongSan_CNConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNongsanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNongsanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNongsanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNongsanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_DonDatHang> CT_DonDatHangs
		{
			get
			{
				return this.GetTable<CT_DonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<DonDatHang> DonDatHangs
		{
			get
			{
				return this.GetTable<DonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiSanPham> LoaiSanPhams
		{
			get
			{
				return this.GetTable<LoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<QuanTri> QuanTris
		{
			get
			{
				return this.GetTable<QuanTri>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_DonDatHang")]
	public partial class CT_DonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_DDH;
		
		private int _Ma_SP;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _Giaban;
		
		private EntityRef<DonDatHang> _DonDatHang;
		
		private EntityRef<SanPham> _SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_DDHChanging(int value);
    partial void OnMa_DDHChanged();
    partial void OnMa_SPChanging(int value);
    partial void OnMa_SPChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnGiabanChanging(System.Nullable<decimal> value);
    partial void OnGiabanChanged();
    #endregion
		
		public CT_DonDatHang()
		{
			this._DonDatHang = default(EntityRef<DonDatHang>);
			this._SanPham = default(EntityRef<SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_DDH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ma_DDH
		{
			get
			{
				return this._Ma_DDH;
			}
			set
			{
				if ((this._Ma_DDH != value))
				{
					if (this._DonDatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_DDHChanging(value);
					this.SendPropertyChanging();
					this._Ma_DDH = value;
					this.SendPropertyChanged("Ma_DDH");
					this.OnMa_DDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ma_SP
		{
			get
			{
				return this._Ma_SP;
			}
			set
			{
				if ((this._Ma_SP != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_SPChanging(value);
					this.SendPropertyChanging();
					this._Ma_SP = value;
					this.SendPropertyChanged("Ma_SP");
					this.OnMa_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giaban", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Giaban
		{
			get
			{
				return this._Giaban;
			}
			set
			{
				if ((this._Giaban != value))
				{
					this.OnGiabanChanging(value);
					this.SendPropertyChanging();
					this._Giaban = value;
					this.SendPropertyChanged("Giaban");
					this.OnGiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_CT_DonDatHang", Storage="_DonDatHang", ThisKey="Ma_DDH", OtherKey="Ma_DDH", IsForeignKey=true)]
		public DonDatHang DonDatHang
		{
			get
			{
				return this._DonDatHang.Entity;
			}
			set
			{
				DonDatHang previousValue = this._DonDatHang.Entity;
				if (((previousValue != value) 
							|| (this._DonDatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonDatHang.Entity = null;
						previousValue.CT_DonDatHangs.Remove(this);
					}
					this._DonDatHang.Entity = value;
					if ((value != null))
					{
						value.CT_DonDatHangs.Add(this);
						this._Ma_DDH = value.Ma_DDH;
					}
					else
					{
						this._Ma_DDH = default(int);
					}
					this.SendPropertyChanged("DonDatHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_CT_DonDatHang", Storage="_SanPham", ThisKey="Ma_SP", OtherKey="Ma_SP", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.CT_DonDatHangs.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.CT_DonDatHangs.Add(this);
						this._Ma_SP = value.Ma_SP;
					}
					else
					{
						this._Ma_SP = default(int);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonDatHang")]
	public partial class DonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_DDH;
		
		private System.Nullable<decimal> _TongTien;
		
		private System.Nullable<bool> _Dathanhtoan;
		
		private System.Nullable<System.DateTime> _Ngaydat;
		
		private int _Ma_ND;
		
		private EntitySet<CT_DonDatHang> _CT_DonDatHangs;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_DDHChanging(int value);
    partial void OnMa_DDHChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    partial void OnDathanhtoanChanging(System.Nullable<bool> value);
    partial void OnDathanhtoanChanged();
    partial void OnNgaydatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydatChanged();
    partial void OnMa_NDChanging(int value);
    partial void OnMa_NDChanged();
    #endregion
		
		public DonDatHang()
		{
			this._CT_DonDatHangs = new EntitySet<CT_DonDatHang>(new Action<CT_DonDatHang>(this.attach_CT_DonDatHangs), new Action<CT_DonDatHang>(this.detach_CT_DonDatHangs));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_DDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_DDH
		{
			get
			{
				return this._Ma_DDH;
			}
			set
			{
				if ((this._Ma_DDH != value))
				{
					this.OnMa_DDHChanging(value);
					this.SendPropertyChanging();
					this._Ma_DDH = value;
					this.SendPropertyChanged("Ma_DDH");
					this.OnMa_DDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dathanhtoan", DbType="Bit")]
		public System.Nullable<bool> Dathanhtoan
		{
			get
			{
				return this._Dathanhtoan;
			}
			set
			{
				if ((this._Dathanhtoan != value))
				{
					this.OnDathanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Dathanhtoan = value;
					this.SendPropertyChanged("Dathanhtoan");
					this.OnDathanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydat
		{
			get
			{
				return this._Ngaydat;
			}
			set
			{
				if ((this._Ngaydat != value))
				{
					this.OnNgaydatChanging(value);
					this.SendPropertyChanging();
					this._Ngaydat = value;
					this.SendPropertyChanged("Ngaydat");
					this.OnNgaydatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_ND", DbType="Int NOT NULL")]
		public int Ma_ND
		{
			get
			{
				return this._Ma_ND;
			}
			set
			{
				if ((this._Ma_ND != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_NDChanging(value);
					this.SendPropertyChanging();
					this._Ma_ND = value;
					this.SendPropertyChanged("Ma_ND");
					this.OnMa_NDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_CT_DonDatHang", Storage="_CT_DonDatHangs", ThisKey="Ma_DDH", OtherKey="Ma_DDH")]
		public EntitySet<CT_DonDatHang> CT_DonDatHangs
		{
			get
			{
				return this._CT_DonDatHangs;
			}
			set
			{
				this._CT_DonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DonDatHang", Storage="_NguoiDung", ThisKey="Ma_ND", OtherKey="Ma_ND", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.DonDatHangs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.DonDatHangs.Add(this);
						this._Ma_ND = value.Ma_ND;
					}
					else
					{
						this._Ma_ND = default(int);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DonDatHangs(CT_DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHang = this;
		}
		
		private void detach_CT_DonDatHangs(CT_DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiSanPham")]
	public partial class LoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_LSP;
		
		private string _Ten_LSP;
		
		private EntitySet<SanPham> _SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_LSPChanging(int value);
    partial void OnMa_LSPChanged();
    partial void OnTen_LSPChanging(string value);
    partial void OnTen_LSPChanged();
    #endregion
		
		public LoaiSanPham()
		{
			this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_LSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_LSP
		{
			get
			{
				return this._Ma_LSP;
			}
			set
			{
				if ((this._Ma_LSP != value))
				{
					this.OnMa_LSPChanging(value);
					this.SendPropertyChanging();
					this._Ma_LSP = value;
					this.SendPropertyChanged("Ma_LSP");
					this.OnMa_LSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_LSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_LSP
		{
			get
			{
				return this._Ten_LSP;
			}
			set
			{
				if ((this._Ten_LSP != value))
				{
					this.OnTen_LSPChanging(value);
					this.SendPropertyChanging();
					this._Ten_LSP = value;
					this.SendPropertyChanged("Ten_LSP");
					this.OnTen_LSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSanPham_SanPham", Storage="_SanPhams", ThisKey="Ma_LSP", OtherKey="Ma_LSP")]
		public EntitySet<SanPham> SanPhams
		{
			get
			{
				return this._SanPhams;
			}
			set
			{
				this._SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSanPham = this;
		}
		
		private void detach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_NCC;
		
		private string _Ten_NCC;
		
		private string _Gmail_NCC;
		
		private string _Diachi_NCC;
		
		private string _Dienthoai_NCC;
		
		private EntitySet<SanPham> _SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_NCCChanging(int value);
    partial void OnMa_NCCChanged();
    partial void OnTen_NCCChanging(string value);
    partial void OnTen_NCCChanged();
    partial void OnGmail_NCCChanging(string value);
    partial void OnGmail_NCCChanged();
    partial void OnDiachi_NCCChanging(string value);
    partial void OnDiachi_NCCChanged();
    partial void OnDienthoai_NCCChanging(string value);
    partial void OnDienthoai_NCCChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_NCC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_NCC
		{
			get
			{
				return this._Ma_NCC;
			}
			set
			{
				if ((this._Ma_NCC != value))
				{
					this.OnMa_NCCChanging(value);
					this.SendPropertyChanging();
					this._Ma_NCC = value;
					this.SendPropertyChanged("Ma_NCC");
					this.OnMa_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_NCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_NCC
		{
			get
			{
				return this._Ten_NCC;
			}
			set
			{
				if ((this._Ten_NCC != value))
				{
					this.OnTen_NCCChanging(value);
					this.SendPropertyChanging();
					this._Ten_NCC = value;
					this.SendPropertyChanged("Ten_NCC");
					this.OnTen_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gmail_NCC", DbType="VarChar(100)")]
		public string Gmail_NCC
		{
			get
			{
				return this._Gmail_NCC;
			}
			set
			{
				if ((this._Gmail_NCC != value))
				{
					this.OnGmail_NCCChanging(value);
					this.SendPropertyChanging();
					this._Gmail_NCC = value;
					this.SendPropertyChanged("Gmail_NCC");
					this.OnGmail_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi_NCC", DbType="NVarChar(200)")]
		public string Diachi_NCC
		{
			get
			{
				return this._Diachi_NCC;
			}
			set
			{
				if ((this._Diachi_NCC != value))
				{
					this.OnDiachi_NCCChanging(value);
					this.SendPropertyChanging();
					this._Diachi_NCC = value;
					this.SendPropertyChanged("Diachi_NCC");
					this.OnDiachi_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dienthoai_NCC", DbType="VarChar(15)")]
		public string Dienthoai_NCC
		{
			get
			{
				return this._Dienthoai_NCC;
			}
			set
			{
				if ((this._Dienthoai_NCC != value))
				{
					this.OnDienthoai_NCCChanging(value);
					this.SendPropertyChanging();
					this._Dienthoai_NCC = value;
					this.SendPropertyChanged("Dienthoai_NCC");
					this.OnDienthoai_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_SanPham", Storage="_SanPhams", ThisKey="Ma_NCC", OtherKey="Ma_NCC")]
		public EntitySet<SanPham> SanPhams
		{
			get
			{
				return this._SanPhams;
			}
			set
			{
				this._SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_ND;
		
		private string _Hoten_ND;
		
		private string _Taikhoan_ND;
		
		private string _Matkhau_ND;
		
		private string _Gmail_ND;
		
		private string _Diachi_ND;
		
		private string _Dienthoai_ND;
		
		private EntitySet<DonDatHang> _DonDatHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_NDChanging(int value);
    partial void OnMa_NDChanged();
    partial void OnHoten_NDChanging(string value);
    partial void OnHoten_NDChanged();
    partial void OnTaikhoan_NDChanging(string value);
    partial void OnTaikhoan_NDChanged();
    partial void OnMatkhau_NDChanging(string value);
    partial void OnMatkhau_NDChanged();
    partial void OnGmail_NDChanging(string value);
    partial void OnGmail_NDChanged();
    partial void OnDiachi_NDChanging(string value);
    partial void OnDiachi_NDChanged();
    partial void OnDienthoai_NDChanging(string value);
    partial void OnDienthoai_NDChanged();
    #endregion
		
		public NguoiDung()
		{
			this._DonDatHangs = new EntitySet<DonDatHang>(new Action<DonDatHang>(this.attach_DonDatHangs), new Action<DonDatHang>(this.detach_DonDatHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_ND", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_ND
		{
			get
			{
				return this._Ma_ND;
			}
			set
			{
				if ((this._Ma_ND != value))
				{
					this.OnMa_NDChanging(value);
					this.SendPropertyChanging();
					this._Ma_ND = value;
					this.SendPropertyChanged("Ma_ND");
					this.OnMa_NDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten_ND", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hoten_ND
		{
			get
			{
				return this._Hoten_ND;
			}
			set
			{
				if ((this._Hoten_ND != value))
				{
					this.OnHoten_NDChanging(value);
					this.SendPropertyChanging();
					this._Hoten_ND = value;
					this.SendPropertyChanged("Hoten_ND");
					this.OnHoten_NDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan_ND", DbType="VarChar(50)")]
		public string Taikhoan_ND
		{
			get
			{
				return this._Taikhoan_ND;
			}
			set
			{
				if ((this._Taikhoan_ND != value))
				{
					this.OnTaikhoan_NDChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan_ND = value;
					this.SendPropertyChanged("Taikhoan_ND");
					this.OnTaikhoan_NDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau_ND", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Matkhau_ND
		{
			get
			{
				return this._Matkhau_ND;
			}
			set
			{
				if ((this._Matkhau_ND != value))
				{
					this.OnMatkhau_NDChanging(value);
					this.SendPropertyChanging();
					this._Matkhau_ND = value;
					this.SendPropertyChanged("Matkhau_ND");
					this.OnMatkhau_NDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gmail_ND", DbType="VarChar(100)")]
		public string Gmail_ND
		{
			get
			{
				return this._Gmail_ND;
			}
			set
			{
				if ((this._Gmail_ND != value))
				{
					this.OnGmail_NDChanging(value);
					this.SendPropertyChanging();
					this._Gmail_ND = value;
					this.SendPropertyChanged("Gmail_ND");
					this.OnGmail_NDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi_ND", DbType="NVarChar(200)")]
		public string Diachi_ND
		{
			get
			{
				return this._Diachi_ND;
			}
			set
			{
				if ((this._Diachi_ND != value))
				{
					this.OnDiachi_NDChanging(value);
					this.SendPropertyChanging();
					this._Diachi_ND = value;
					this.SendPropertyChanged("Diachi_ND");
					this.OnDiachi_NDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dienthoai_ND", DbType="VarChar(15)")]
		public string Dienthoai_ND
		{
			get
			{
				return this._Dienthoai_ND;
			}
			set
			{
				if ((this._Dienthoai_ND != value))
				{
					this.OnDienthoai_NDChanging(value);
					this.SendPropertyChanging();
					this._Dienthoai_ND = value;
					this.SendPropertyChanged("Dienthoai_ND");
					this.OnDienthoai_NDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DonDatHang", Storage="_DonDatHangs", ThisKey="Ma_ND", OtherKey="Ma_ND")]
		public EntitySet<DonDatHang> DonDatHangs
		{
			get
			{
				return this._DonDatHangs;
			}
			set
			{
				this._DonDatHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanTri")]
	public partial class QuanTri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_QT;
		
		private string _Hoten_QT;
		
		private string _Taikhoan_QT;
		
		private string _Matkhau_QT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_QTChanging(int value);
    partial void OnMa_QTChanged();
    partial void OnHoten_QTChanging(string value);
    partial void OnHoten_QTChanged();
    partial void OnTaikhoan_QTChanging(string value);
    partial void OnTaikhoan_QTChanged();
    partial void OnMatkhau_QTChanging(string value);
    partial void OnMatkhau_QTChanged();
    #endregion
		
		public QuanTri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_QT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_QT
		{
			get
			{
				return this._Ma_QT;
			}
			set
			{
				if ((this._Ma_QT != value))
				{
					this.OnMa_QTChanging(value);
					this.SendPropertyChanging();
					this._Ma_QT = value;
					this.SendPropertyChanged("Ma_QT");
					this.OnMa_QTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten_QT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hoten_QT
		{
			get
			{
				return this._Hoten_QT;
			}
			set
			{
				if ((this._Hoten_QT != value))
				{
					this.OnHoten_QTChanging(value);
					this.SendPropertyChanging();
					this._Hoten_QT = value;
					this.SendPropertyChanged("Hoten_QT");
					this.OnHoten_QTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan_QT", DbType="VarChar(50)")]
		public string Taikhoan_QT
		{
			get
			{
				return this._Taikhoan_QT;
			}
			set
			{
				if ((this._Taikhoan_QT != value))
				{
					this.OnTaikhoan_QTChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan_QT = value;
					this.SendPropertyChanged("Taikhoan_QT");
					this.OnTaikhoan_QTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau_QT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Matkhau_QT
		{
			get
			{
				return this._Matkhau_QT;
			}
			set
			{
				if ((this._Matkhau_QT != value))
				{
					this.OnMatkhau_QTChanging(value);
					this.SendPropertyChanging();
					this._Matkhau_QT = value;
					this.SendPropertyChanged("Matkhau_QT");
					this.OnMatkhau_QTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_SP;
		
		private int _Ma_LSP;
		
		private int _Ma_NCC;
		
		private string _Ten_SP;
		
		private System.Nullable<decimal> _Giaban;
		
		private string _Hinhanh;
		
		private System.Nullable<System.DateTime> _Ngaydangban;
		
		private System.Nullable<int> _Soluongton;
		
		private System.Nullable<bool> _Tinhtrang;
		
		private EntitySet<CT_DonDatHang> _CT_DonDatHangs;
		
		private EntityRef<LoaiSanPham> _LoaiSanPham;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_SPChanging(int value);
    partial void OnMa_SPChanged();
    partial void OnMa_LSPChanging(int value);
    partial void OnMa_LSPChanged();
    partial void OnMa_NCCChanging(int value);
    partial void OnMa_NCCChanged();
    partial void OnTen_SPChanging(string value);
    partial void OnTen_SPChanged();
    partial void OnGiabanChanging(System.Nullable<decimal> value);
    partial void OnGiabanChanged();
    partial void OnHinhanhChanging(string value);
    partial void OnHinhanhChanged();
    partial void OnNgaydangbanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydangbanChanged();
    partial void OnSoluongtonChanging(System.Nullable<int> value);
    partial void OnSoluongtonChanged();
    partial void OnTinhtrangChanging(System.Nullable<bool> value);
    partial void OnTinhtrangChanged();
    #endregion
		
		public SanPham()
		{
			this._CT_DonDatHangs = new EntitySet<CT_DonDatHang>(new Action<CT_DonDatHang>(this.attach_CT_DonDatHangs), new Action<CT_DonDatHang>(this.detach_CT_DonDatHangs));
			this._LoaiSanPham = default(EntityRef<LoaiSanPham>);
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_SP
		{
			get
			{
				return this._Ma_SP;
			}
			set
			{
				if ((this._Ma_SP != value))
				{
					this.OnMa_SPChanging(value);
					this.SendPropertyChanging();
					this._Ma_SP = value;
					this.SendPropertyChanged("Ma_SP");
					this.OnMa_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_LSP", DbType="Int NOT NULL")]
		public int Ma_LSP
		{
			get
			{
				return this._Ma_LSP;
			}
			set
			{
				if ((this._Ma_LSP != value))
				{
					if (this._LoaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_LSPChanging(value);
					this.SendPropertyChanging();
					this._Ma_LSP = value;
					this.SendPropertyChanged("Ma_LSP");
					this.OnMa_LSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_NCC", DbType="Int NOT NULL")]
		public int Ma_NCC
		{
			get
			{
				return this._Ma_NCC;
			}
			set
			{
				if ((this._Ma_NCC != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_NCCChanging(value);
					this.SendPropertyChanging();
					this._Ma_NCC = value;
					this.SendPropertyChanged("Ma_NCC");
					this.OnMa_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_SP", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten_SP
		{
			get
			{
				return this._Ten_SP;
			}
			set
			{
				if ((this._Ten_SP != value))
				{
					this.OnTen_SPChanging(value);
					this.SendPropertyChanging();
					this._Ten_SP = value;
					this.SendPropertyChanged("Ten_SP");
					this.OnTen_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giaban", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Giaban
		{
			get
			{
				return this._Giaban;
			}
			set
			{
				if ((this._Giaban != value))
				{
					this.OnGiabanChanging(value);
					this.SendPropertyChanging();
					this._Giaban = value;
					this.SendPropertyChanged("Giaban");
					this.OnGiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="NVarChar(MAX)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this.OnHinhanhChanging(value);
					this.SendPropertyChanging();
					this._Hinhanh = value;
					this.SendPropertyChanged("Hinhanh");
					this.OnHinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydangban", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydangban
		{
			get
			{
				return this._Ngaydangban;
			}
			set
			{
				if ((this._Ngaydangban != value))
				{
					this.OnNgaydangbanChanging(value);
					this.SendPropertyChanging();
					this._Ngaydangban = value;
					this.SendPropertyChanged("Ngaydangban");
					this.OnNgaydangbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongton", DbType="Int")]
		public System.Nullable<int> Soluongton
		{
			get
			{
				return this._Soluongton;
			}
			set
			{
				if ((this._Soluongton != value))
				{
					this.OnSoluongtonChanging(value);
					this.SendPropertyChanging();
					this._Soluongton = value;
					this.SendPropertyChanged("Soluongton");
					this.OnSoluongtonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang", DbType="Bit")]
		public System.Nullable<bool> Tinhtrang
		{
			get
			{
				return this._Tinhtrang;
			}
			set
			{
				if ((this._Tinhtrang != value))
				{
					this.OnTinhtrangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang = value;
					this.SendPropertyChanged("Tinhtrang");
					this.OnTinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_CT_DonDatHang", Storage="_CT_DonDatHangs", ThisKey="Ma_SP", OtherKey="Ma_SP")]
		public EntitySet<CT_DonDatHang> CT_DonDatHangs
		{
			get
			{
				return this._CT_DonDatHangs;
			}
			set
			{
				this._CT_DonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSanPham_SanPham", Storage="_LoaiSanPham", ThisKey="Ma_LSP", OtherKey="Ma_LSP", IsForeignKey=true)]
		public LoaiSanPham LoaiSanPham
		{
			get
			{
				return this._LoaiSanPham.Entity;
			}
			set
			{
				LoaiSanPham previousValue = this._LoaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._LoaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiSanPham.Entity = null;
						previousValue.SanPhams.Remove(this);
					}
					this._LoaiSanPham.Entity = value;
					if ((value != null))
					{
						value.SanPhams.Add(this);
						this._Ma_LSP = value.Ma_LSP;
					}
					else
					{
						this._Ma_LSP = default(int);
					}
					this.SendPropertyChanged("LoaiSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_SanPham", Storage="_NhaCungCap", ThisKey="Ma_NCC", OtherKey="Ma_NCC", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.SanPhams.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.SanPhams.Add(this);
						this._Ma_NCC = value.Ma_NCC;
					}
					else
					{
						this._Ma_NCC = default(int);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DonDatHangs(CT_DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_CT_DonDatHangs(CT_DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
	}
}
#pragma warning restore 1591
